### ISSUE TITLE
Add CodiMD pad for FAQ

### ISSUE THREAD

**Issue by ketsapiwiq** [Uptime-Formation/vnc_server_spawner#5]
Add HackMd pad for FaQ
(with let's encypt)
```yaml
version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.2.0
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database/codimd
      - CMD_USECDN=false
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
```
> https://hackmd.io/s/codimd-docker-deployment#Using-docker-compose-to-setup-CodiMD
